/* StockBot v29 archive/remove + filters */
(()=>{'use strict';const $=id=>document.getElementById(id);
async function archive(id){const reason=prompt('Remove this item from active inventory? Optional reason:','');if(reason===null)return;const {error}=await sb.from('inventory_items').update({archived_at:new Date().toISOString(),archive_reason:reason||null}).eq('id',id);if(error)return toast(error.message);await load();try{closeEditor()}catch(_){}toast('Item moved to Removed / Archived')}
async function restore(id){const {error}=await sb.from('inventory_items').update({archived_at:null,archive_reason:null}).eq('id',id);if(error)return toast(error.message);await load();renderRemoved();toast('Item restored')}
function active(){return (window.items||items||[]).filter(x=>!x.archived_at)}function removed(){return (window.items||items||[]).filter(x=>!!x.archived_at)}
function installEditor(){if(!$('product')?.classList.contains('editorOpen')||$('removeItem'))return;const card=$('save')?.closest('.card');if(!card||!window.current?.id)return;const b=document.createElement('button');b.id='removeItem';b.className='btn danger';b.style='width:100%;margin-top:10px';b.textContent='Remove Item';b.onclick=()=>archive(window.current.id);card.appendChild(b)}
function installFilter(){const d=$('inventoryDashboard');if(!d||$('testFilter'))return;const row=d.querySelector('.row');if(!row)return;const s=document.createElement('select');s.id='testFilter';s.innerHTML='<option value="">All Testing Status</option><option value="need_to_test">Need to Test</option><option value="verified_working">Verified Working</option><option value="not_working_issue">Not Working / Issue</option><option value="not_applicable">Not Applicable</option>';row.appendChild(s);s.onchange=()=>{const val=s.value;d.querySelectorAll('#inventorySheet tbody tr').forEach(tr=>{const x=(window.items||items||[]).find(i=>i.id===tr.dataset.id);tr.style.display=(!val||x?.testing_status===val)&&!x?.archived_at?'':'none'})};const btn=document.createElement('button');btn.className='btn';btn.textContent='Removed / Archived';btn.onclick=renderRemoved;d.querySelectorAll('.row')[1]?.appendChild(btn)}
function renderRemoved(){let box=$('removedBox');if(!box){box=document.createElement('div');box.id='removedBox';box.className='card';$('inventoryDashboard')?.appendChild(box)}const a=removed();box.innerHTML='<h3>Removed / Archived</h3>'+(a.length?a.map(x=>'<div class="item"><b>'+esc(x.product_name)+'</b><div class="muted">'+esc(x.upc||'')+(x.archive_reason?' · '+esc(x.archive_reason):'')+'</div><button class="btn restoreV29" data-id="'+x.id+'">Restore</button></div>').join(''):'<p class="muted">No removed items.</p>');box.querySelectorAll('.restoreV29').forEach(b=>b.onclick=()=>restore(b.dataset.id));box.scrollIntoView({behavior:'smooth'})}
const oldList=window.renderList;if(typeof oldList==='function')window.renderList=function(){oldList();document.querySelectorAll('#list .item').forEach(el=>{const id=el.querySelector('.open')?.dataset.id,x=(window.items||items||[]).find(i=>i.id===id);if(x?.archived_at)el.remove()})};
const obs=new MutationObserver(()=>{installEditor();installFilter()});obs.observe(document.documentElement,{childList:true,subtree:true});installEditor();installFilter();window.StockBotArchiveV29={archive,restore,renderRemoved};
})();