/* StockBot intake v28 — testing verification + Done saves */
(()=>{'use strict';const $=id=>document.getElementById(id);let saving=false;
function install(){const p=$('product');if(!p?.classList.contains('editorOpen'))return;const notes=$('notes');if(!notes)return;
 if(!$('testingStatus')){const wrap=document.createElement('div');wrap.id='testingWrap';wrap.style.marginTop='10px';wrap.innerHTML='<label>Testing / Verification</label><select id="testingStatus"><option value="">Select testing status…</option><option value="need_to_test">Need to Test</option><option value="verified_working">✓ Verified Working</option><option value="not_working_issue">⚠ Not Working / Issue</option><option value="not_applicable">Not Applicable</option></select><div class="muted" style="margin-top:5px">Keep this separate from cosmetic condition.</div>';notes.parentElement.insertBefore(wrap,notes)}
 if(window.current?.testing_status&&$('testingStatus'))$('testingStatus').value=window.current.testing_status;
 const close=$('closeEditor'),save=$('save');if(close){close.textContent='Done';close.title='Save & Sync';close.onclick=async e=>{e.preventDefault();await saveAndClose()}}if(save){save.textContent='Save & Sync';save.onclick=async e=>{e.preventDefault();await saveKeepOpen()}}
}
function payload(){return {testing_status:$('testingStatus')?.value||null}}
async function persistExtra(id){if(!id)return;const {error}=await sb.from('inventory_items').update(payload()).eq('id',id);if(error)throw error}
async function saveCore(){if(saving)return null;saving=true;try{const isNew=!window.current?.id;const name=isNew?$('pname')?.value.trim():window.current?.product_name;if(!name){toast('Product name is required');return null}let base={owner_id:user.id,product_name:name,upc:isNew?($('pupc')?.value.trim()||null):window.current.upc,expected_qty:+$('expected').value||0,received_qty:+$('received').value||0,available_qty:+$('received').value||0,is_bulk:(+$('expected').value||0)>1,is_manual_add:isNew?true:window.current.is_manual_add,condition_grade:window.condition||condition||null,condition_notes:$('notes')?.value.trim()||null,suggested_price:$('price')?.value?+$('price').value:null,unit_cost:$('cost')?.value?+$('cost').value:null,status:(+$('received').value||0)>0?'received':'unreceived',received_at:(+$('received').value||0)>0?new Date().toISOString():null,testing_status:$('testingStatus')?.value||null};let result=isNew?await sb.from('inventory_items').insert(base).select().single():await sb.from('inventory_items').update(base).eq('id',window.current.id).select().single();if(result.error)throw result.error;window.current=result.data;current=result.data;return result.data}catch(e){toast('Save failed: '+(e.message||e));return null}finally{saving=false}}
async function saveKeepOpen(){const row=await saveCore();if(!row)return;await load();toast('Saved & synced to cloud');openItem(row.id)}
async function saveAndClose(){const row=await saveCore();if(!row)return;try{if(window.StockBotInventoryV26?.uploadPending)await window.StockBotInventoryV26.uploadPending(row.id)}catch(e){console.error(e);toast('Item saved; photo upload needs attention')}await load();if(typeof closeEditor==='function')closeEditor();showView('receive');toast('Done — saved & synced')}
const obs=new MutationObserver(install);obs.observe(document.documentElement,{childList:true,subtree:true});install();window.StockBotIntakeV28={install,saveAndClose,saveKeepOpen};
})();