/* StockBot v32 — scan sold item + record sale */
(()=>{'use strict';const $=id=>document.getElementById(id);let saleItem=null;
function install(){if($('salesV32'))return;const receive=$('receive');if(!receive)return;const card=document.createElement('div');card.id='salesV32';card.className='card';card.style.marginTop='12px';card.innerHTML='<div class="title">Record a Sale</div><div class="muted">Scan the sold item, then record quantity, amount received and payment method.</div><button class="btn green" id="scanSoldItem" style="width:100%;margin-top:10px">▦ Scan Sold Item</button><button class="btn" id="salesHistoryBtn" style="width:100%;margin-top:8px">View Sales History</button><div id="saleForm" class="hidden" style="margin-top:12px"></div><div id="salesHistory" class="hidden" style="margin-top:12px"></div>';receive.appendChild(card);$('scanSoldItem').onclick=scanSale;$('salesHistoryBtn').onclick=history}
async function scanSale(){window.scanTarget='sale';if(window.StockBotScannerV25?.start)return window.StockBotScannerV25.start('sale');toast('Scanner is not ready')}
const original=window.handleScannedUPC;window.handleScannedUPC=async function(code,target){if(target==='sale'||window.scanTarget==='sale'){await choose(code);window.scanTarget='lookup';return}return original(code,target)};
async function choose(upc){const a=(window.items||items||[]).filter(x=>x.upc===upc&&!x.archived_at);if(!a.length){toast('UPC not found in StockBot inventory');return}saleItem=a[0];form()}
function form(){const x=saleItem,f=$('saleForm');if(!x||!f)return;const avail=Number(x.available_qty??x.received_qty??0);f.classList.remove('hidden');f.innerHTML='<div class="item"><b>'+esc(x.product_name||'Item')+'</b><div class="muted">UPC '+esc(x.upc||'')+' · '+avail+' available</div></div><div class="row" style="margin-top:9px"><div><label>Quantity sold</label><input id="soldQty" type="number" min="1" max="'+avail+'" value="1"></div><div><label>Total amount received</label><input id="soldAmount" type="number" min="0" step=".01" placeholder="$0.00"></div></div><label style="margin-top:9px">Payment method</label><select id="paymentMethod"><option value="cash">Cash</option><option value="venmo">Venmo</option><option value="zelle">Zelle</option><option value="paypal">PayPal</option><option value="cash_app">Cash App</option><option value="card">Card</option><option value="other">Other</option></select><label style="margin-top:9px">Sale notes (optional)</label><textarea id="saleNotes" rows="2" placeholder="Buyer, pickup notes, discount, etc."></textarea><button class="btn green" id="recordSale" style="width:100%;margin-top:10px">Save Sale & Update Inventory</button>';$('recordSale').onclick=save}
async function save(){if(!saleItem)return;const qty=+$('soldQty').value||0,amount=+$('soldAmount').value,avail=Number(saleItem.available_qty??saleItem.received_qty??0);if(qty<1)return toast('Enter quantity sold');if(qty>avail)return toast('Only '+avail+' available');if(!Number.isFinite(amount)||amount<0)return toast('Enter the total amount received');const method=$('paymentMethod').value,notes=$('saleNotes').value.trim()||null,newAvail=avail-qty;const session=(await sb.auth.getSession()).data.session;if(!session)return toast('Please sign in again');const sale={owner_id:session.user.id,inventory_item_id:saleItem.id,quantity:qty,sale_amount:amount,payment_method:method,notes};const ins=await sb.from('sales_transactions').insert(sale);if(ins.error)return toast('Sale not saved: '+ins.error.message);const upd=await sb.from('inventory_items').update({available_qty:newAvail,status:newAvail<=0?'sold':saleItem.status}).eq('id',saleItem.id);if(upd.error)return toast('Sale recorded, but inventory update failed: '+upd.error.message);toast('Sale saved · '+qty+' sold · '+money(amount)+' · '+method.replace('_',' '));saleItem=null;$('saleForm').classList.add('hidden');await load();if(window.StockBotInventoryV26?.renderSheet)window.StockBotInventoryV26.renderSheet()}
async function history(){const h=$('salesHistory');if(!h)return;if(!h.classList.contains('hidden')){h.classList.add('hidden');return}const {data,error}=await sb.from('sales_transactions').select('*').order('sold_at',{ascending:false}).limit(100);if(error)return toast(error.message);const map=Object.fromEntries((window.items||items||[]).map(x=>[x.id,x]));h.innerHTML='<div class="title">Recent Sales</div>'+((data||[]).map(s=>{const x=map[s.inventory_item_id]||{};return '<div class="item"><b>'+esc(x.product_name||'Inventory item')+'</b><div class="muted">'+new Date(s.sold_at).toLocaleString()+' · Qty '+s.quantity+' · '+money(s.sale_amount)+' · '+esc(s.payment_method.replace('_',' '))+'</div></div>'}).join('')||'<p class="muted">No sales recorded yet.</p>');h.classList.remove('hidden')}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();window.StockBotSalesV32={choose,history};
})();