/* StockBot scanner v25 — native iPhone preview, one camera owner */
(()=>{'use strict';
let stream=null,running=false,target='lookup',raf=0,detector=null,zx=null,controls=null;
const $=id=>document.getElementById(id);const valid=x=>{x=String(x||'').replace(/\D/g,'');return [8,12,13,14].includes(x.length)?x:''};
async function stop(){running=false;cancelAnimationFrame(raf);try{controls?.stop()}catch(_){}controls=null;zx=null;try{stream?.getTracks().forEach(t=>t.stop())}catch(_){}stream=null;const v=$('scanPreview');if(v){try{v.pause()}catch(_){}v.srcObject=null;v.style.display='block'}$('scanModal')?.classList.add('hidden')}
async function hit(code){code=valid(code);if(!code||!running)return;running=false;if(navigator.vibrate)navigator.vibrate(80);await stop();await window.handleScannedUPC(code,target)}
async function detectLoop(v){if(!running)return;try{if(detector&&v.readyState>=2){const a=await detector.detect(v);if(a?.[0]?.rawValue){await hit(a[0].rawValue);return}}}catch(_){}raf=requestAnimationFrame(()=>detectLoop(v))}
async function start(t='lookup'){target=t;window.scanTarget=t;await stop();const modal=$('scanModal'),v=$('scanPreview'),status=$('scanStatus');if(!modal||!v)return;modal.classList.remove('hidden');v.style.display='block';if(status)status.textContent='Opening rear camera…';try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});v.srcObject=stream;v.muted=true;v.playsInline=true;v.setAttribute('playsinline','');await v.play();await new Promise((res,rej)=>{if(v.videoWidth>0)return res();let n=0;const f=()=>{if(v.videoWidth>0)return res();if(++n>60)return rej(new Error('Camera opened but preview did not start'));requestAnimationFrame(f)};f()});running=true;if(status)status.textContent='Camera ready — center the UPC in the green box';if('BarcodeDetector'in window){try{detector=new BarcodeDetector({formats:['upc_a','upc_e','ean_13','ean_8']});detectLoop(v);return}catch(_){detector=null}}if(window.ZXingBrowser){zx=new ZXingBrowser.BrowserMultiFormatReader();controls=await zx.decodeFromVideoElement(v,(result)=>{if(result)hit(result.getText?result.getText():result.text)});return}throw new Error('Barcode reader unavailable')}catch(e){console.error('scanner v25',e);if(status)status.textContent='Camera error: '+(e?.message||e);try{toast('Camera error: '+(e?.message||e))}catch(_){}}}
function wire(){const b=$('scanBtn');if(b)b.onclick=()=>start('lookup');const c=$('closeScan');if(c)c.onclick=stop;const p=$('photoFallback');if(p)p.style.display='';document.querySelectorAll('#scanNewUPC').forEach(b=>b.onclick=()=>start('editor'))}
new MutationObserver(wire).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();window.StockBotScannerV25={start,stop};
})();