/* StockBot voice v21 — MediaRecorder -> Supabase transcription. DOES NOT touch scanner/video. */
(()=>{'use strict';
let recording=false,rec=null,stream=null,chunks=[],timer=null,lastEditor=false;
const $=id=>document.getElementById(id), say=s=>{try{toast(s)}catch(_){}};
function apply(data){const q=data?.quantity,c=data?.condition,text=data?.text||'';const r=$('received');if(q!=null&&r){r.value=String(q);r.dispatchEvent(new Event('input',{bubbles:true}));r.dispatchEvent(new Event('change',{bubbles:true}))}if(c){window.condition=c;document.querySelectorAll('#conditions button').forEach(b=>b.classList.toggle('sel',b.dataset.c===c))}const st=$('voiceStatusV21');if(st)st.textContent='Heard: “'+text+'”'+(q!=null?' · quantity '+q:'')+(c?' · '+c:'');say('Applied'+(q!=null?' · quantity '+q:'')+(c?' · '+c:''))}
function setState(s){const st=$('voiceStatusV21');if(st)st.textContent=s;const b=$('speakNotes');if(b)b.textContent=recording?'⏹ Stop Voice':'🎙 Speak Item Info'}
async function transcribe(blob){const session=(await sb.auth.getSession()).data.session;if(!session?.access_token)throw new Error('Please sign in again');const fd=new FormData();const ext=(blob.type||'').includes('mp4')?'m4a':'webm';fd.append('audio',blob,'stockbot-voice.'+ext);const res=await fetch('https://aiwdfltusdzhrrbblvfi.supabase.co/functions/v1/stockbot-transcribe',{method:'POST',headers:{Authorization:'Bearer '+session.access_token},body:fd});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||('Transcription failed ('+res.status+')'));return d}
async function finish(){if(!recording)return;recording=false;clearTimeout(timer);setState('Processing voice…');try{if(rec&&rec.state!=='inactive')rec.stop()}catch(e){console.warn(e)}}
async function start(){if(recording)return;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Audio recording is unavailable in this browser');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];let mime='';for(const t of ['audio/mp4','audio/webm;codecs=opus','audio/webm']){if(MediaRecorder.isTypeSupported?.(t)){mime=t;break}}rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onerror=e=>{recording=false;stream?.getTracks().forEach(t=>t.stop());setState('Microphone error: '+(e.error?.message||'recording failed'))};rec.onstop=async()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;try{const blob=new Blob(chunks,{type:rec.mimeType||mime||'audio/webm'});if(blob.size<500)throw new Error('No voice audio was captured');const d=await transcribe(blob);apply(d)}catch(e){console.error('StockBot voice',e);setState('Voice error: '+(e.message||e));say('Voice error: '+(e.message||e))}finally{recording=false;const b=$('speakNotes');if(b)b.textContent='🎙 Speak Item Info'}};rec.start(250);recording=true;setState('🎙 Listening — say “quantity 3, condition good”');say('Listening…');timer=setTimeout(finish,5000)}catch(e){recording=false;stream?.getTracks().forEach(t=>t.stop());stream=null;setState('Voice error: '+(e.message||e));say('Voice error: '+(e.message||e))}}
function install(){const editor=$('product')?.classList.contains('editorOpen');if(!editor){lastEditor=false;return}if(!$('voiceStatusV21')){const anchor=$('conditions')?.parentElement||$('notes')?.parentElement;if(anchor){const d=document.createElement('div');d.id='voiceStatusV21';d.className='muted';d.style='margin:8px 0';d.textContent='Voice ready';anchor.insertBefore(d,$('notes')||null)}}['voiceQty','speakQty2'].forEach(id=>$(id)?.remove());const b=$('speakNotes');if(b){b.textContent='🎙 Speak Item Info';b.onclick=e=>{e.preventDefault();recording?finish():start()}}if(!lastEditor){lastEditor=true;setTimeout(()=>start(),700)}}
new MutationObserver(install).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});install();window.StockBotVoiceV21={start,finish,apply};
})();