/* StockBot voice v24 — microphone only; never touches camera/video/scanner. */
(()=>{'use strict';
let recording=false,rec=null,mic=null,chunks=[],timer=null,lastEditor=false,autoArmed=true;
const $=id=>document.getElementById(id);const msg=s=>{try{toast(s)}catch(_){}};
function status(s){const x=$('voiceStatusV24');if(x)x.textContent=s;}
function normalizeCondition(s){s=(s||'').toLowerCase();if(/like new|open box/.test(s))return'Like New/Open Box';if(/new|sealed/.test(s))return'New/Sealed';if(/missing/.test(s))return'Missing Parts';if(/fair|damaged|broken/.test(s))return'Fair/Damaged';if(/\bgood\b/.test(s))return'Good';return null}
function apply(d){const text=d?.text||d?.transcript||'';let q=d?.quantity,c=d?.condition;if(q==null){const m=text.match(/(?:quantity|qty|received|count)\s*(?:is|of|:)?\s*(\d+)/i);if(m)q=+m[1]}c=c||normalizeCondition(text);if(q!=null&&$('received')){$('received').value=String(q);$('received').dispatchEvent(new Event('change',{bubbles:true}))}if(c){try{condition=c}catch(_){}window.condition=c;document.querySelectorAll('#conditions button').forEach(b=>b.classList.toggle('sel',b.dataset.c===c))}status('Heard: “'+text+'”'+(q!=null?' · quantity '+q:'')+(c?' · '+c:''));msg('Voice applied'+(q!=null?' · quantity '+q:'')+(c?' · '+c:''))}
function stopMic(){try{mic?.getTracks().forEach(t=>t.stop())}catch(_){}mic=null}
async function transcribe(blob){const session=(await sb.auth.getSession()).data.session;if(!session?.access_token)throw new Error('Please sign in again');const fd=new FormData();fd.append('audio',blob,(blob.type||'').includes('mp4')?'stockbot.m4a':'stockbot.webm');const r=await fetch('https://aiwdfltusdzhrrbblvfi.supabase.co/functions/v1/stockbot-transcribe',{method:'POST',headers:{Authorization:'Bearer '+session.access_token},body:fd});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch(_){d={error:raw}}if(!r.ok)throw new Error(d?.error||('Transcription failed '+r.status));return d}
async function finish(){if(!recording)return;recording=false;clearTimeout(timer);status('Processing voice…');try{if(rec?.state!=='inactive')rec.stop()}catch(e){stopMic();status('Voice error: '+e.message)}}
async function start(){if(recording)return;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Microphone recording is unavailable');status('Requesting microphone…');mic=await navigator.mediaDevices.getUserMedia({audio:true,video:false});chunks=[];let type='';for(const t of ['audio/mp4','audio/webm;codecs=opus','audio/webm'])if(MediaRecorder.isTypeSupported?.(t)){type=t;break}rec=new MediaRecorder(mic,type?{mimeType:type}:undefined);rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onstop=async()=>{stopMic();try{const blob=new Blob(chunks,{type:rec.mimeType||type||'audio/webm'});if(blob.size<300)throw new Error('No speech audio captured');apply(await transcribe(blob))}catch(e){console.error(e);status('Voice error: '+(e.message||e));msg('Voice error: '+(e.message||e))}finally{recording=false;wire()}};rec.start();recording=true;status('🎙 Listening — say “quantity 3, condition good”');wire();timer=setTimeout(finish,4500)}catch(e){recording=false;stopMic();status('Voice error: '+(e.message||e));msg('Voice error: '+(e.message||e));wire()}}
function wire(){const editor=$('product')?.classList.contains('editorOpen');if(!editor){lastEditor=false;autoArmed=true;return}['voiceQty','speakQty2'].forEach(id=>$(id)?.remove());const b=$('speakNotes');if(b){b.textContent=recording?'⏹ Stop Listening':'🎙 Speak Item Info';b.style.width='100%';b.onclick=e=>{e.preventDefault();e.stopPropagation();recording?finish():start()};if(!$('voiceStatusV24')){const d=document.createElement('div');d.id='voiceStatusV24';d.className='muted';d.style.margin='8px 0';d.textContent='Voice ready';b.insertAdjacentElement('afterend',d)}}if(!lastEditor&&autoArmed){lastEditor=true;autoArmed=false;setTimeout(()=>{if($('scanModal')?.classList.contains('hidden')&&!recording)start()},700)}}
new MutationObserver(wire).observe(document.body,{childList:true,subtree:true});wire();window.StockBotVoice={start,finish};
})();