/* StockBot voice intake v16 — iPhone WebKit speech recognition first, audio fallback second */
(()=>{
 const $=id=>document.getElementById(id);let listening=false,recognizer=null,recorder=null,chunks=[],stream=null,timer=null;
 const parse=t=>{const low=String(t||'').toLowerCase();let q=(low.match(/(?:quantity|qty|received|count)\s*(?:is|of|=|:)?\s*(\d+)/i)||[])[1];if(!q){const words={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12};const m=low.match(/(?:quantity|qty|received|count)\s+(one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b/);if(m)q=words[m[1]]}if(q&&$('received')){$('received').value=q;$('received').dispatchEvent(new Event('input',{bubbles:true}))}let c='';if(/like\s*new|open\s*box/.test(low))c='Like New/Open Box';else if(/new|sealed|brand\s*new/.test(low))c='New/Sealed';else if(/missing/.test(low))c='Missing Parts';else if(/fair|damaged|broken/.test(low))c='Fair/Damaged';else if(/\bgood\b/.test(low))c='Good';if(c){window.condition=c;document.querySelectorAll('#conditions button').forEach(b=>b.classList.toggle('sel',b.dataset.c===c))}toast('Voice: '+t);setTimeout(()=>toast('Applied'+(q?' · quantity '+q:'')+(c?' · '+c:'')),1000);return {q,c}}
 function setButton(text){const b=$('speakNotes');if(b){b.textContent=text;b.style.width='100%'}}
 function nativeSpeech(){return window.SpeechRecognition||window.webkitSpeechRecognition}
 async function startNative(){const SR=nativeSpeech();if(!SR)return false;try{recognizer=new SR();recognizer.lang='en-US';recognizer.interimResults=false;recognizer.continuous=false;recognizer.maxAlternatives=1;recognizer.onstart=()=>{listening=true;setButton('🎙 Listening…');toast('Listening — say “quantity 3, condition good”')};recognizer.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript||'';if(t)parse(t)};recognizer.onerror=e=>{console.warn('speech recognition',e.error);toast('Voice error: '+e.error)};recognizer.onend=()=>{listening=false;setButton('🎙 Speak Item Info')};recognizer.start();return true}catch(e){console.warn(e);return false}}
 async function transcribe(blob){const fd=new FormData();fd.append('audio',blob,'voice.'+(blob.type.includes('mp4')?'m4a':'webm'));const session=(await sb.auth.getSession()).data.session;const r=await fetch('https://aiwdfltusdzhrrbblvfi.supabase.co/functions/v1/stockbot-transcribe',{method:'POST',headers:session?{Authorization:'Bearer '+session.access_token}:{},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Voice transcription service unavailable');return d.text||''}
 async function startRecorder(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];const type=MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':'audio/webm';recorder=new MediaRecorder(stream,{mimeType:type});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream?.getTracks().forEach(t=>t.stop());try{toast('Processing voice…');const t=await transcribe(new Blob(chunks,{type}));if(t)parse(t);else toast('No speech detected')}catch(e){toast(e.message)}finally{listening=false;setButton('🎙 Speak Item Info')}};recorder.start();listening=true;setButton('🎙 Listening…');toast('Listening — say “quantity 3, condition good”');timer=setTimeout(()=>{try{recorder.stop()}catch(_){}},5000);return true}catch(e){toast('Microphone error: '+(e.message||e));return false}}
 async function startAuto(){if(listening)return;const ok=await startNative();if(!ok)await startRecorder()}
 function stop(){clearTimeout(timer);try{recognizer?.stop()}catch(_){}try{if(recorder?.state==='recording')recorder.stop()}catch(_){}listening=false}
 function wire(){const b=$('speakNotes');if(b){b.onclick=()=>listening?stop():startAuto();setButton(listening?'🎙 Listening…':'🎙 Speak Item Info')}}
 new MutationObserver(wire).observe(document.documentElement,{subtree:true,childList:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',wire):wire();window.StockBotVoiceV16={parse,startAuto,stop};window.StockBotVoiceV15=window.StockBotVoiceV14=window.StockBotVoiceV16;
})();